### ISSUE TITLE
FRQ 1

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/fastpages2#2]
Implemented all FRQ methods in [AP Calendar](https://github.com/xiaoa0/spring/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/calendar/APCalendar.java)

Debugging 
![](https://raw.githubusercontent.com/xiaoa0/fastpages2/master/images/Screenshot%202022-11-18%20at%208.05.02%20AM.png)

Still working out issues with Postman and running on localhost

**Comment by jm1021** [comment]
2.4
